Nomis/dsos 1596/setup cloudwatch configs
ministryofjustice/modernisation-platform-configuration-management pull request #27
Opened 2023-01-05 16:50 UTC by robertiansweetman

Ensures the cloudwatch agent is installed on Rhel EC2 instances and collects metrics as well as var/log/messages and var/log/secure log lines which will appear against an instance_id in CloudWatch.

Windows instances are not included at the moment.

2023-01-05 16:59 UTC, wullub approved these changes

2023-01-09 11:50 UTC, jnq requested changes
can we keep to convention on file naming?

Windows -> windows
RedHat -> redhat

2023-01-10 12:07 UTC, jnq approved these changes

2023-01-10 13:49 UTC, jnq approved these changes

2023-01-10 13:50 UTC, merged