secretsmanagersecrets for oracle19c
ministryofjustice/modernisation-platform-configuration-management pull request #371
Opened 2023-10-19 16:50 UTC by wullub

secretsmanagersecrets for oracle19c

2023-11-03 15:47 UTC, drobinson-moj requested changes
I don't think it will work as it stands - did you test it?

2023-11-03 15:47 UTC, drobinson-moj commented on ansible/roles/oracle-19c/defaults/main.yml
>      parameter: "/ec2/{{ ec2_name }}/asm-passwords"
Unfortunately I named that differently.  It's "secret" for secretsmanager role and "parameter" for ssm parameter role.  So unless you change the ansible roles, you'll need to cut + paste instead.

2023-11-08 16:03 UTC, robertsweetman submitted a review, later dismissed

2023-11-08 16:22 UTC, robertsweetman approved these changes

2023-11-08 16:58 UTC, drobinson-moj approved these changes

2023-11-08 17:11 UTC, merged